# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kali/Desktop/report-arp-spoof/Cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kali/Desktop/report-arp-spoof

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kali/Desktop/report-arp-spoof/CMakeFiles /home/kali/Desktop/report-arp-spoof//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kali/Desktop/report-arp-spoof/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named report-arp-spoof

# Build rule for target.
report-arp-spoof: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 report-arp-spoof
.PHONY : report-arp-spoof

# fast build rule for target.
report-arp-spoof/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/build
.PHONY : report-arp-spoof/fast

src/AttackerInfo.o: src/AttackerInfo.cpp.o
.PHONY : src/AttackerInfo.o

# target to build an object file
src/AttackerInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/AttackerInfo.cpp.o
.PHONY : src/AttackerInfo.cpp.o

src/AttackerInfo.i: src/AttackerInfo.cpp.i
.PHONY : src/AttackerInfo.i

# target to preprocess a source file
src/AttackerInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/AttackerInfo.cpp.i
.PHONY : src/AttackerInfo.cpp.i

src/AttackerInfo.s: src/AttackerInfo.cpp.s
.PHONY : src/AttackerInfo.s

# target to generate assembly for a file
src/AttackerInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/AttackerInfo.cpp.s
.PHONY : src/AttackerInfo.cpp.s

src/Utill.o: src/Utill.cpp.o
.PHONY : src/Utill.o

# target to build an object file
src/Utill.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/Utill.cpp.o
.PHONY : src/Utill.cpp.o

src/Utill.i: src/Utill.cpp.i
.PHONY : src/Utill.i

# target to preprocess a source file
src/Utill.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/Utill.cpp.i
.PHONY : src/Utill.cpp.i

src/Utill.s: src/Utill.cpp.s
.PHONY : src/Utill.s

# target to generate assembly for a file
src/Utill.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/Utill.cpp.s
.PHONY : src/Utill.cpp.s

src/arphdr.o: src/arphdr.cpp.o
.PHONY : src/arphdr.o

# target to build an object file
src/arphdr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/arphdr.cpp.o
.PHONY : src/arphdr.cpp.o

src/arphdr.i: src/arphdr.cpp.i
.PHONY : src/arphdr.i

# target to preprocess a source file
src/arphdr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/arphdr.cpp.i
.PHONY : src/arphdr.cpp.i

src/arphdr.s: src/arphdr.cpp.s
.PHONY : src/arphdr.s

# target to generate assembly for a file
src/arphdr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/arphdr.cpp.s
.PHONY : src/arphdr.cpp.s

src/ethhdr.o: src/ethhdr.cpp.o
.PHONY : src/ethhdr.o

# target to build an object file
src/ethhdr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/ethhdr.cpp.o
.PHONY : src/ethhdr.cpp.o

src/ethhdr.i: src/ethhdr.cpp.i
.PHONY : src/ethhdr.i

# target to preprocess a source file
src/ethhdr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/ethhdr.cpp.i
.PHONY : src/ethhdr.cpp.i

src/ethhdr.s: src/ethhdr.cpp.s
.PHONY : src/ethhdr.s

# target to generate assembly for a file
src/ethhdr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/ethhdr.cpp.s
.PHONY : src/ethhdr.cpp.s

src/ip.o: src/ip.cpp.o
.PHONY : src/ip.o

# target to build an object file
src/ip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/ip.cpp.o
.PHONY : src/ip.cpp.o

src/ip.i: src/ip.cpp.i
.PHONY : src/ip.i

# target to preprocess a source file
src/ip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/ip.cpp.i
.PHONY : src/ip.cpp.i

src/ip.s: src/ip.cpp.s
.PHONY : src/ip.s

# target to generate assembly for a file
src/ip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/ip.cpp.s
.PHONY : src/ip.cpp.s

src/mac.o: src/mac.cpp.o
.PHONY : src/mac.o

# target to build an object file
src/mac.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/mac.cpp.o
.PHONY : src/mac.cpp.o

src/mac.i: src/mac.cpp.i
.PHONY : src/mac.i

# target to preprocess a source file
src/mac.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/mac.cpp.i
.PHONY : src/mac.cpp.i

src/mac.s: src/mac.cpp.s
.PHONY : src/mac.s

# target to generate assembly for a file
src/mac.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/mac.cpp.s
.PHONY : src/mac.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/report-arp-spoof.dir/build.make CMakeFiles/report-arp-spoof.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... report-arp-spoof"
	@echo "... src/AttackerInfo.o"
	@echo "... src/AttackerInfo.i"
	@echo "... src/AttackerInfo.s"
	@echo "... src/Utill.o"
	@echo "... src/Utill.i"
	@echo "... src/Utill.s"
	@echo "... src/arphdr.o"
	@echo "... src/arphdr.i"
	@echo "... src/arphdr.s"
	@echo "... src/ethhdr.o"
	@echo "... src/ethhdr.i"
	@echo "... src/ethhdr.s"
	@echo "... src/ip.o"
	@echo "... src/ip.i"
	@echo "... src/ip.s"
	@echo "... src/mac.o"
	@echo "... src/mac.i"
	@echo "... src/mac.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

